_target_: src.models.timm_module.Timm_LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.1
  epochs: ${trainer.max_epochs}
  steps_per_epoch: 425

net:
  _target_: timm.models.create_model
  model_name: resnet18
  pretrained: true
  in_chans: 3
  num_classes: ${model.num_class}

num_class: 6

learning_rate: 0.001
